//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantBook.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int PriceID { get; set; }
        public int SymbolID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> PriceOpen { get; set; }
        public Nullable<double> PriceHigh { get; set; }
        public Nullable<double> PriceLow { get; set; }
        public Nullable<double> PriceClose { get; set; }
        public Nullable<double> PriceAdj { get; set; }
        public Nullable<double> Volume { get; set; }
    
        public virtual Symbol Symbol { get; set; }
    }
}
